name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Ktlint
        run: ./gradlew ktlint
      - name: Checkstyle
        run: ./gradlew checkstyle
      - name: Lint
        run: ./gradlew lintRelease

      # Check if there has been a binary incompatible change to the API.
      # If this change is intentional, run `./gradlew apiDump` and commit the new API files.
      - name: Check binary compatibility
        run: ./gradlew apiCheck

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: unit-test-report
          path: stripe/build/reports/tests/testDebugUnitTest/

  end-to-end-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Unit tests
        run: ./gradlew :stripe-test-e2e:testDebugUnitTest
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: unit-test-report
          path: stripe-test-e2e/build/reports/tests/testDebugUnitTest/
      - name: Notify failure endpoint
        id: notifyFailureEndpoint
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.SDK_FAILURE_NOTIFICATION_ENDPOINT }}
          method: 'POST'
          data: |
            |
            {
              "project": "RUN_MOBILESDK",
              "summary": "stripe-android E2E test failed",
              "description": "Please ACK this ticket and investigate the failure. $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
            }
      - name: Show Response
        run: echo ${{ steps.notifyFailureEndpoint.outputs.response }}