name: CI Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  end-to-end-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Notify failure endpoint
        id: notifyFailureEndpoint
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.SDK_FAILURE_NOTIFICATION_ENDPOINT }}
          method: 'POST'
          data: |
            {
              "project": "RUN_MOBILESDK",
              "summary": "stripe-android E2E test failed",
              "description": "Please ACK this ticket and investigate the failure. See https://github.com/stripe/stripe-android/actions/runs/${{ github.run_id }}"
            }
      - name: Show Response
        run: echo ${{ steps.notifyFailureEndpoint.outputs.response }}